#!/bin/sh

set -e
set -u
set -o pipefail

if [ $# -eq 0 ]; then
  echo "Usage: $0 HOSTNAME"
  exit 1
fi

HOSTNAME=$1
COMMAND="openssl s_client -showcerts -servername $HOSTNAME -connect $HOSTNAME:443"

set +e

$COMMAND </dev/null 2>/dev/null | openssl x509 -noout -dates -subject -issuer
$COMMAND </dev/null 2>/dev/null | openssl x509 -noout -text | grep -A1 'Subject Alternative Name'

exit 0
