#!/bin/sh

set -e
set -u

# one argument
if [ $# -eq 0 ]; then
    echo 1>&2 Usage: $0 UUID
    exit 127
fi

UUID=$1

set +e # allow commands to fail (e.g. the machine is already off)
set -x

VBoxManage controlvm $UUID poweroff
VBoxManage unregistervm --delete $UUID
