---
- hosts: osx
  vars:
    pgdata: "{{ lookup('env','PGDATA') }}"
  tasks:
    - name: change timezone to utc
      lineinfile: >
        backup=yes
        dest="{{ pgdata }}/postgresql.conf"
        regexp="^timezone = 'Europe/Stockholm'$"
        line="timezone = 'UTC'"
      notify: reload postgres

  handlers:
    - name: reload postgres
      shell: pg_ctl reload
