---
- hosts: localhost
  gather_facts: no
  tags: always
  tasks:
    - debug: msg="[site.yml] task with always"

- hosts: localhost
  gather_facts: no
  tasks:
    - debug: msg="[site.yml] task with no tags"

- hosts: localhost
  gather_facts: no
  tags: standard
  roles:
    - standard

- hosts: localhost
  gather_facts: no
  roles:
    - role: extra
      tags: extra
      check_mode: "{{ ansible_check_mode or 'extra' not in ansible_run_tags }}"
