#!/usr/bin/env ruby

# frozen_string_literal: true

# strings to test with
#
# secret for encrypted
# SESSION_SECRET=3b6729f943db2acbc339d3d2d8a41080fd89631c3c9db1354d5cf7255e644299
#
# rack 2 (only HMAC)
# BAh7B0kiD3Nlc3Npb25faWQGOgZFVG86HVJhY2s6OlNlc3Npb246OlNlc3Npb25JZAY6D0BwdWJsaWNfaWRJIkUzZjUxYjVhOTgwNWJiYTdlZGFkM2E1OTM1ZmFhMjY1OWQyMzUwNmUyNmY2OWQ3OWY5MWExZGZhY2Q2YzZmYzk5BjsARkkiCGZvbwY7AFRJIghiYXIGOwBU--77cba9f77e635450a5c34eb8d442f9ac5cd3f84c
#
# rack 2 (rack-protection >= 3.0.0) (encrypted)
# AaI4P1WOpfeFZgkaD%2BlscAeL0b0g9hQS3iK%2BTfox7%2FjpruiZq1KjOa3lru97K%2FXxzwfUe1v%2BgTLnbVZXua5eet5UUhuJUB5fAsUgwonTAbKaQsNI3h9GUxRdEEzIU9fkqfSjEeJk3DU7Q11k96Ev4L8f1Hd%2BJvBTYWZDEk7WEDWHd4ly0cwwEUrjq2PqmiBONgYp3GEuPkB3R%2FFALHTGj7r8JVIwAHw5vDuemYZB3zWamgEQsoangVui%2BuD%2FMabvsh8E%2F4%2Fmc6S%2FaF%2BKcB3%2FubS0x4Fobzj7zznUWRllRAXXag%3D%3D--bgnU0Sm3iosvb3eb--AoQtXGVLTZfJCkKHpyvVYQ%3D%3D
#
# rack 3 (rack-session >= 2.0.0) (encrypted) (run with KEY=nil)
# AbeMnOJBBiHeTrTyH-2Tl1JnsYR-8t_v3cy5O_b9JBJehPWrQtD0o8D6ehhmGRDOMaXy9nVhcAlRRAHz5AM2I6QQcIne_6fqYnwH_16rfLZhFpwWgUeT0YMOt2Nxewl6bibLwEfkTVYCkrVBb20BXCArM0Wc2JDuysnOiJx7JgWJGocPqvISN6efqvQBXUK9z8ZxL4ZHctNF2dJGSGugb4AqJ18oezCaxmA8YXV182gnKz2DwLV7W320H5Lv7ttQapY9isXUq_9S9SHVooDK67mEmLMBFv5JZqRXWLT36Dr8XHTX-lAb16wBbxTgNsgupA%3D%3D
#
# rack 3 (rack-session > 2.0.0) (AEAD (V2) encrypted)
# Asfm1NH6St8zwT%2B3SnHsxofmYtSDmpdWiXfbPyPqiIC6AjmLLwxnnGaqJBy9v93qNpQnKGvDU9rjIgFWd%2Bjska7qrovLD5zgGn0y0acXatJ07PWAiZWesZa%2Fqg2gmA%2Fw7w9qjPHhsjMk7Msc38aBN3bHK75JmPLD%2Buy4OxDN59guH6T2Nh7Yis8QF%2BICfOfkV7jxDQ0dKTW6Yf3fZQ%3D%3D

# all outputs goes to stderr except the cookie hash so we can pipe to jq if we want
#
# pbpaste | decode_rack_cookie | jq

# this also works
#
# export S=3b6729f943db2acbc339d3d2d8a41080fd89631c3c9db1354d5cf7255e644299
# decode_rack_cookie --encrypt foo

$stdout.sync = true
$stderr.sync = true

DEBUG = ENV.key?("DEBUG") # wont work with pipe to jq
RACK_SESSION = ENV.fetch("RACK_SESSION", ARGV.first == "--encrypt" ? "2" : "0")

warn "Loading gems..."
require "bundler/inline"

gemfile(DEBUG) do
  source "https://rubygems.org"
  gem "base64"
  gem "json"
  gem "uri"
  case RACK_SESSION
  when "0", "1"
    gem "rack", "< 3", require: "rack/session/abstract/id"
    gem "rack-protection", "< 4"
  when "2"
    # works with rack-session main too (Rack::Session::Encryptor::V1)
    gem "rack-session", ">= 2", require: "rack/session/cookie"
  when "head", "main"
    gem "rack-session", github: "rack/rack-session", require: "rack/session/cookie"
  end
end

def warn_errors(*errors)
  warn "\nErrors reported"
  errors.each_with_index do |error, idx|
    warn "Error #{idx}"
    warn error.full_message
    warn
  end
end

def bold_yellow(str)
  "\e[33m\e[1m#{str}\e[0m"
end

def bold_green(str)
  "\e[32m\e[1m#{str}\e[0m"
end

def print_decoded_cookie(cookie_value)
  return if cookie_value.nil?
  warn
  puts decode_cookie(cookie_value).to_json
  warn
  warn bold_green("Cookie was decoded successfully!")
rescue StandardError => decode_error # rubocop:disable Naming/RescuedExceptionsVariableName
  if session_secret.nil?
    warn bold_yellow("Set environment variables S or SESSION_SECRET to try to decrypt cookie")
    warn_errors(decode_error)
    return
  end
  warn "Failed to decode, trying to decrypt cookie..."
  warn
  begin
    if decrypted_cookie = decrypt_cookie(cookie_value)
      warn bold_green("Cookie was decrypted successfully!")
      warn ""
      puts decrypted_cookie.to_json
    else
      warn bold_yellow("Run with RACK_SESSION={1,2,main} to decrypt cookies")
      warn bold_yellow("  * 1    - encrypted by rack-protection (sinatra) >=3.0.0")
      warn bold_yellow("  * 2    - encrypted by rack-session 2.0.0")
      warn bold_yellow("  * main - encrypted by rack-session main branch")
      warn_errors(decode_error)
    end
  rescue => decrypt_error
    warn_errors(decode_error, decrypt_error)
    if ENV["KEY"].to_s == ""
      warn bold_yellow \
        "Try this (https://github.com/rack/rack-session/issues/35)\n\n\texport KEY=nil"
    end
  end
end

def decode_cookie(cookie_value)
  Marshal.load(Base64.decode64(URI.decode_uri_component(cookie_value))) # rubocop:disable Security/MarshalLoad
end

def decrypt_cookie(data)
  case RACK_SESSION
  when "0", "1"
    handle_rack_protection_cookie(data)
  else
    handle_rack_session_cookie(data)
  end
end

# Rack::Protection::EncryptedCookie (rack-protection >= 3.0.0)
#   encode, encrypt
#   decrypt, decode
def handle_rack_protection_cookie(cookie_value)
  hex_secret      = session_secret
  secret          = [hex_secret].pack("H*") # raw byte string
  coder           = Rack::Protection::EncryptedCookie::Marshal.new
  encrypted_data  = URI.decode_uri_component(cookie_value)
  decrypted_value = Rack::Protection::Encryptor.decrypt_message(encrypted_data, secret)

  coder.decode(decrypted_value)
end

# Rack::Session::Cookie (rack-session == 2.0.0)
# Rack::Session::Cookie (rack-session > 2.0.0, https://github.com/rack/rack-session/pull/23)
#   encrypt
#   decrypt
def handle_rack_session_cookie(cookie_value)
  encryptor      = Rack::Session::Encryptor.new(session_secret, purpose:)
  encrypted_data = URI.decode_uri_component(cookie_value)

  encryptor.decrypt(encrypted_data)
end

def encrypted_cookie(value)
  encryptor = Rack::Session::Encryptor.new(session_secret, purpose:)

  encryptor.encrypt(value)
end

def purpose
  return if ENV["KEY"] == "nil"

  ENV.fetch("KEY", "rack.session")
end

def session_secret
  ENV["S"] || ENV["SESSION_SECRET"]
end

warn "All gems loaded. Exit with Ctrl-C (^C)"
warn

if ARGV.any?
  first_arg = ARGV.shift
  if first_arg == "--encrypt"
    payload = ARGV.shift

    puts encrypted_cookie(payload)
  else
    print_decoded_cookie(first_arg)
  end
  exit
elsif $stdin.stat.pipe?
  print_decoded_cookie($stdin.read.chomp)
  exit
end

begin
  loop do
    puts "Paste the cookie value and press Enter:"
    print_decoded_cookie($stdin.gets)
    puts
  end
rescue Interrupt
  exit
end
