# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"

group :test do
  gem "rake"
  gem "rack-test"
  # gem "rspec"
  gem "rspec", "= 3.8.0"
  gem "rspec-core", "= 3.8.0"
  gem "rspec-expectations", "= 3.8.2"
  gem "rspec-mocks", "= 3.8.0"
  gem "rspec-support", "= 3.8.0"
end
