#!/usr/bin/env zsh -l

# https://stackoverflow.com/questions/13468481/when-to-use-set-e/13478622#13478622
set -e
set -u
set -o pipefail

local ruby_path

for ruby_path in $RUBIES; do
  local ruby_version=$(basename $ruby_path)

  # chruby-exec $ruby_version -- ruby -v & # test/development
  chruby-exec $ruby_version -- bin/update-ruby-gems $ruby_version &
done

wait

# development notes
# change RUBIES in ~/.zprofile to test with fewer rubies
#
#    # Ruby
#    export RUBIES=(~/.fake_rubies/*)
#
# symlink real rubies
#
# cd ~/.fake_rubies
# ln -s ../.rubies/jruby-9.1.13.0
# ...
#
# jruby-9.1.13.0@ -> ../.rubies/jruby-9.1.13.0
# ruby-2.2.8@ -> ../.rubies/ruby-2.2.8
# ruby-2.2.9@ -> ../.rubies/ruby-2.2.9
